Repository Slowers-Team/Slowers-App, pull requests merged in 2024-11, with the labels that each got.

#112 Fixing the bug related to running frontend in production mode
  backend/application/application.go
  backend/main.go
Labels: type:bug, priority:high

#114 Update routes and affected components in frontend
  frontend/src/App.jsx
  frontend/src/components/NavigationBar.jsx
  frontend/src/components/NewSiteForm.jsx
  frontend/src/components/ProtectedRoute.jsx
  frontend/src/components/SiteFlexbox.jsx
  frontend/src/layouts/GrowerLayout.jsx
  frontend/src/pages/GrowerFlowerPage.jsx
  frontend/src/pages/GrowerHomePage.jsx
  frontend/src/pages/GrowerSitesPage.jsx
  frontend/src/translations.json
Labels: type:enhancement, priority:high

#109 107 missing unit tests for backend api routes
  backend/apitests/flowers_test.go
  backend/apitests/users_test.go
Labels: type:enhancement

#113 110 missing unit tests for database functions in backend
  backend/apitests/flowers_test.go
  backend/apitests/sites_test.go
  backend/apitests/users_test.go
  backend/application/application.go
  backend/database/tests/flower_test.go
  backend/database/tests/site_test.go
  backend/database/tests/user_test.go
  backend/testdata/flower.go
  backend/testdata/site.go
  backend/testdata/user.go
Labels: type:enhancement

#117 108 user can view updated navigation UI
  frontend/src/App.css
  frontend/src/components/NavigationBar.jsx
  frontend/src/layouts/GrowerLayout.jsx
  frontend/src/layouts/RetailerLayout.jsx
  frontend/src/pages/SitePage.jsx
Labels: type:enhancement, priority:medium

#124 115 running frontend in production mode breaks when refreshing
  backend/application/application.go
Labels: type:bug, priority:high

#106 93 user is not logged in automatically after registration
  backend/apitests/users_test.go
  backend/database/database.go
  backend/database/tests/user_test.go
  backend/database/user.go
  backend/handlers/user.go
  frontend/src/App.jsx
  frontend/src/pages/RegisterPage.jsx
Labels: type:bug, priority:high

#119 116 instructions for writing backend unit tests
  documentation/backend_unit_tests.md
  documentation/backend_unit_tests/api_route_add_file.md
  documentation/backend_unit_tests/api_route_add_test.md
  documentation/backend_unit_tests/db_function_add_file.md
  documentation/backend_unit_tests/db_function_add_test.md
Labels: documentation

#139 137 incorrect success alert when user registration fails
  frontend/src/components/RegisterForm.jsx
  frontend/src/pages/RegisterPage.jsx
Labels: type:bug

#147 131 grower can view updated flowers tab
  frontend/src/components/FlowerForm.jsx
  frontend/src/components/grower/AddFlower.jsx
  frontend/src/components/grower/AddFlowerUpdate.jsx
  frontend/src/components/grower/GrowerFlowerList.jsx
  frontend/src/pages/GrowerFlowerPage.jsx
  frontend/src/translations.json
  frontend/tests/components/AddFlower.test.jsx
  frontend/tests/components/FlowerForm.test.jsx
Labels: type:enhancement, priority:high

#144 141 grower can set the quantity of flowers
  backend/apitests/flowers_test.go
  backend/database/flower.go
  backend/database/tests/flower_test.go
  backend/handlers/flower.go
  backend/testdata/flower.go
  frontend/src/components/FlowerForm.jsx
  frontend/src/components/FlowerModal.jsx
  frontend/src/components/grower/GrowerFlowerList.jsx
  frontend/src/components/retailer/RetailerFlowerList.jsx
  frontend/src/translations.json
  frontend/tests/components/FlowerForm.test.jsx
  frontend/tests/services/flowers.test.js
Labels: priority:high, type:feature
