Repository Slowers-Team/Slowers-App, pull requests merged in 2024-09, with the labels that each got.

#14 13 fixing readme
  README.md
Labels: documentation

#19 18 refactor frontend into smaller components
  frontend/eslint.config.js
  frontend/src/App.jsx
  frontend/src/components/FlowerForm.jsx
  frontend/src/components/FlowerList.jsx
  frontend/src/services/flowers.js
Labels: enhancement

#26 25 missing labels in forms
  frontend/.gitignore
  frontend/src/components/FlowerForm.jsx
  frontend/src/components/RegisterForm.jsx
Labels: bug, enhancement

#27 15 setting up automatic deployment to the staging server
  .github/workflows/staging.yml
  Containerfile
  backend/Dockerfile
  frontend/Dockerfile
Labels: enhancement
