Repository Slowers-Team/Slowers-App, pull requests merged in 2024-12, with the labels that each got.

#156 152 grower can manage flower images
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/FlowerModal.jsx
  frontend/src/components/image/FlowerImageGallery.jsx
  frontend/src/components/image/FlowerImageTab.jsx
  frontend/src/components/image/ImageGallery.css
  frontend/src/translations.json
  frontend/tests/components/image/AddImage.test.jsx
  frontend/tests/components/image/FlowerImageGallery.test.jsx
  frontend/tests/components/image/FlowerImageTab.test.jsx
  frontend/tests/components/image/ImageForm.test.jsx
Labels: priority:high, type:feature

#159 158 grower can view updated site images
  frontend/src/components/image/FlowerImageTab.jsx
  frontend/src/components/image/ImageGallery.jsx
  frontend/src/components/image/SiteImagesCarousel.jsx
  frontend/src/pages/GrowerHomePage.jsx
  frontend/src/pages/GrowerImagesPage.jsx
  frontend/src/translations.json
  frontend/tests/components/image/ImageGallery.test.jsx
Labels: type:enhancement, priority:high

#157 134 grower can modify flower information
  backend/apitests/flowers_test.go
  backend/application/application.go
  backend/database/database.go
  backend/database/flower.go
  backend/database/tests/flower_test.go
  backend/handlers/flower.go
  frontend/src/components/FlowerModal.jsx
  frontend/src/components/ModifyFlowerForm.jsx
  frontend/src/components/grower/GrowerFlowerList.jsx
  frontend/src/layouts/Grower.css
  frontend/src/pages/GrowerFlowerPage.jsx
  frontend/src/services/flowers.js
  frontend/src/translations.json
  frontend/tests/components/ModifyFlowerForm.test.jsx
  frontend/tests/services/flowers.test.js
Labels: priority:high, type:feature

#165 160 grower can delete multiple flowers
  backend/apitests/flowers_test.go
  backend/application/application.go
  backend/database/database.go
  backend/database/flower.go
  backend/database/tests/flower_test.go
  backend/handlers/flower.go
  backend/utils/json.go
  frontend/src/pages/GrowerFlowerPage.jsx
  frontend/src/services/flowers.js
  frontend/src/translations.json
  frontend/tests/services/flowers.test.js
Labels: type:enhancement, priority:high

#163 155 user can filter and sort flower lists
  frontend/src/components/FlowerList.jsx
  frontend/src/components/grower/GrowerFlowerList.jsx
  frontend/src/components/retailer/RetailerFlowerList.jsx
  frontend/src/layouts/Grower.css
  frontend/src/layouts/Retailer.css
  frontend/src/pages/SitePage.jsx
  frontend/src/translations.json
  frontend/tests/components/RetailerFlowerlist.test.jsx
Labels: priority:high, type:feature

#170 Add staging server configuration files
  config/staging-server/deployment-slowers-mongo.yaml
  config/staging-server/deploymentconfig-slowers-backend.yaml
  config/staging-server/deploymentconfig-slowers-frontend.yaml
  config/staging-server/imagestream-slowers-backend.yaml
  config/staging-server/imagestream-slowers-frontend.yaml
  config/staging-server/imagestream-slowers-mongo.yaml
  config/staging-server/imagestreamtag-slowers-backend_latest.yaml
  config/staging-server/imagestreamtag-slowers-frontend_latest.yaml
  config/staging-server/imagestreamtag-slowers-mongo_latest.yaml
  config/staging-server/persistentvolumeclaim-slowers-image-storage-claim.yaml
  config/staging-server/persistentvolumeclaim-slowers-mongo-claim.yaml
  config/staging-server/route-slowers-backend.yaml
  config/staging-server/route-slowers-frontend.yaml
  config/staging-server/service-slowers-backend.yaml
  config/staging-server/service-slowers-frontend.yaml
  config/staging-server/service-slowers-mongo.yaml
Labels: type:enhancement, priority:medium

#172 166 changing button labels to icons
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/FlowerForm.jsx
  frontend/src/components/FlowerInfoTab.jsx
  frontend/src/components/FlowerModal.jsx
  frontend/src/components/LangSelect.jsx
  frontend/src/components/LogInForm.jsx
  frontend/src/components/ModifyFlowerForm.jsx
  frontend/src/components/NavigationBar.jsx
  frontend/src/components/NewSiteForm.jsx
  frontend/src/components/RegisterForm.jsx
  frontend/src/components/SiteFlexbox.jsx
  frontend/src/components/grower/AddFlower.jsx
  frontend/src/components/grower/GrowerFlowerList.jsx
  frontend/src/components/image/AddImage.jsx
  frontend/src/components/image/ImageForm.jsx
  frontend/src/components/image/ImageGallery.jsx
  frontend/src/components/retailer/RetailerFlowerList.jsx
  frontend/src/pages/GrowerFlowerPage.jsx
  frontend/src/pages/GrowerSitesPage.jsx
  frontend/tests/components/AddFlower.test.jsx
  frontend/tests/components/LangSelect.test.jsx
  frontend/tests/components/LogInForm.test.jsx
  frontend/tests/components/RegisterForm.test.jsx
  frontend/tests/components/RetailerFlowerlist.test.jsx
  frontend/tests/components/image/AddImage.test.jsx
  frontend/tests/components/image/FlowerImageTab.test.jsx
Labels: type:enhancement, priority:high

#176 162 user can see flower images in the flower list
  backend/apitests/images_test.go
  backend/application/application.go
  backend/database/database.go
  backend/database/image.go
  backend/database/tests/image_test.go
  backend/handlers/image.go
  frontend/src/components/grower/GrowerFlowerList.jsx
  frontend/src/components/image/FlowerImageTab.jsx
  frontend/src/components/image/FlowerListImage.css
  frontend/src/components/retailer/RetailerFlowerList.jsx
  frontend/src/services/images.js
  frontend/src/translations.json
Labels: priority:high, type:feature

#177 148 user can see site images in the site flexbox
  frontend/src/Misc.css
  frontend/src/components/FlowerForm.jsx
  frontend/src/components/ModifyFlowerForm.jsx
  frontend/src/components/NewSiteForm.jsx
  frontend/src/components/SiteFlexbox.jsx
  frontend/src/components/grower/GrowerFlowerList.jsx
  frontend/src/components/image/ImageForm.jsx
  frontend/src/components/image/ImageGallery.jsx
  frontend/src/pages/GrowerImagesPage.jsx
  frontend/src/pages/GrowerSitesPage.jsx
  frontend/tests/components/SiteFlexbox.test.jsx
Labels: priority:high, type:feature

#181 178 site improvements
  frontend/src/App.css
  frontend/src/Misc.css
  frontend/src/components/AddSite.jsx
  frontend/src/components/FlowerForm.jsx
  frontend/src/components/NewSiteForm.jsx
  frontend/src/components/SiteMasonry.jsx
  frontend/src/components/grower/GrowerFlowerList.jsx
  frontend/src/components/retailer/RetailerFlowerList.jsx
  frontend/src/layouts/GrowerLayout.jsx
  frontend/src/pages/GrowerFlowerPage.jsx
  frontend/src/pages/GrowerHomePage.jsx
  frontend/src/pages/GrowerImagesPage.jsx
  frontend/src/pages/GrowerSitesPage.jsx
  frontend/src/pages/RetailerFlowerPage.jsx
  frontend/src/pages/RetailerHomePage.jsx
  frontend/src/pages/TermsPage.jsx
  frontend/src/pages/UserPage.jsx
  frontend/tests/components/AddSite.test.jsx
  frontend/tests/components/SiteFlexbox.test.jsx
  frontend/tests/components/SiteMasonry.test.jsx
Labels: type:enhancement, priority:high, type:feature

#182 168 unifying main theme
  frontend/src/App.css
  frontend/src/Misc.css
  frontend/src/components/FlowerForm.jsx
  frontend/src/components/FlowerInfoTab.jsx
  frontend/src/components/FlowerModal.css
  frontend/src/components/FlowerModal.jsx
  frontend/src/components/LangSelect.jsx
  frontend/src/components/LogInForm.jsx
  frontend/src/components/NavigationBar.jsx
  frontend/src/components/NewSiteForm.jsx
  frontend/src/components/RegisterForm.jsx
  frontend/src/components/grower/GrowerFlowerList.jsx
  frontend/src/components/image/AddImage.jsx
  frontend/src/components/image/ImageForm.jsx
  frontend/src/components/image/ImageGallery.jsx
  frontend/src/components/retailer/RetailerFlowerList.jsx
  frontend/src/layouts/Grower.css
  frontend/src/layouts/GrowerLayout.jsx
  frontend/src/layouts/Retailer.css
  frontend/src/layouts/RetailerLayout.jsx
  frontend/src/pages/GrowerFlowerPage.jsx
  frontend/src/pages/LogInPage.jsx
  frontend/src/pages/RegisterPage.jsx
  frontend/src/pages/SitePage.jsx
  frontend/src/translations.json
  frontend/src/utils.js
  frontend/tests/components/LangSelect.test.jsx
Labels: type:enhancement, priority:high
