Repository Slowers-Team/Slowers-App, pull requests merged in 2024-10, with the labels that each got.

#44 Fixing the bug found in issue #40
  frontend/src/pages/HomePage.jsx
Labels: bug

#47 37 create farm view
  backend/main.go
  backend/site.go
  frontend/src/App.jsx
  frontend/src/Misc.css
  frontend/src/components/NewSiteForm.jsx
  frontend/src/components/SiteFlexbox.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/SitePage.jsx
  frontend/src/services/sites.js
Labels: enhancement

#52 51 grower can add flowers to sites
  backend/go.mod
  backend/go.sum
  backend/main.go
  backend/site.go
  frontend/src/App.jsx
  frontend/src/Misc.css
  frontend/src/components/FlowerForm.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/SitePage.jsx
  frontend/src/services/flowers.js
Labels: enhancement

#55 Fix the bug found in issue#54
  backend/site.go
Labels: bug

#46 16 setting up unit testing for frontend
  frontend/eslint.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/services/flowers.js
  frontend/src/services/token.js
  frontend/tests/components/FlowerForm.test.jsx
  frontend/tests/components/FlowerList.test.jsx
  frontend/tests/components/LogIn.test.jsx
  frontend/tests/components/RegisterForm.test.jsx
  frontend/tests/services/flowers.test.js
  frontend/tests/services/users.test.js
  frontend/tests/testSetup.js
  frontend/vite.config.js
Labels: enhancement

#62 59 user can view terms of use privacy policy and other legal material
  frontend/src/App.jsx
  frontend/src/Misc.css
  frontend/src/components/RegisterForm.jsx
  frontend/src/components/TermsWindow.jsx
  frontend/src/pages/TermsPage.jsx
Labels: enhancement

#58 Update deleteFlower to also delete the flower from its sites list
  backend/main.go
Labels: bug

#49 34 refactor backend into smaller components
  backend/application/application.go
  backend/config.go
  backend/database/database.go
  backend/database/flower.go
  backend/database/site.go
  backend/database/user.go
  backend/handlers/flower.go
  backend/handlers/handlers.go
  backend/handlers/site.go
  backend/handlers/user.go
  backend/main.go
  backend/site.go
  backend/utils/utils.go
Labels: enhancement

#69 35 setting up unit testing for backend
  .gitignore
  README.md
  backend/.mockery.yaml
  backend/apitests/flowers_test.go
  backend/apitests/sites_test.go
  backend/apitests/users_test.go
  backend/application/application.go
  backend/database/tests/flower_test.go
  backend/database/tests/site_test.go
  backend/database/tests/user_test.go
  backend/database/user.go
  backend/go.mod
  backend/go.sum
  backend/handlers/flower.go
  backend/handlers/site.go
  backend/handlers/user.go
  backend/testdata/flower.go
  backend/testdata/site.go
  backend/testdata/user.go
  backend/testutils/database.go
  backend/testutils/http.go
  backend/utils/json.go
  backend/utils/utils.go
Labels: enhancement

#74 53 retailer can view the list of all flowers
  backend/database/database.go
  backend/database/flower.go
  backend/database/user.go
  backend/handlers/flower.go
  frontend/src/App.jsx
  frontend/src/components/retailer/RetailerFlowerList.jsx
  frontend/src/layouts/Retailer.css
  frontend/src/layouts/RetailerLayout.jsx
  frontend/src/pages/RetailerFlowerPage.jsx
  frontend/src/pages/RetailerHomePage.jsx
Labels: enhancement

#76 71 user can change the language support for internationalization
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/FlowerForm.jsx
  frontend/src/components/FlowerList.jsx
  frontend/src/components/LogIn.jsx
  frontend/src/components/NewSiteForm.jsx
  frontend/src/components/RegisterForm.jsx
  frontend/src/components/SiteFlexbox.jsx
  frontend/src/components/grower/GrowerFlowerList.jsx
  frontend/src/components/retailer/RetailerFlowerList.jsx
  frontend/src/i18n.js
  frontend/src/layouts/GrowerLayout.jsx
  frontend/src/layouts/RetailerLayout.jsx
  frontend/src/main.jsx
  frontend/src/pages/GrowerFlowerPage.jsx
  frontend/src/pages/GrowerHomePage.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/RegisterPage.jsx
  frontend/src/pages/RetailerFlowerPage.jsx
  frontend/src/pages/RetailerHomePage.jsx
  frontend/src/pages/SitePage.jsx
  frontend/src/pages/TermsPage.jsx
  frontend/src/translations.json
Labels: enhancement

#80 79 internationalization broke frontend unit tests
  frontend/tests/components/LogIn.test.jsx
  frontend/tests/components/RegisterForm.test.jsx
  frontend/vite.config.js
Labels: bug

#92 67 UI improvements
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/Misc.css
  frontend/src/components/FlowerForm.jsx
  frontend/src/components/LogIn.jsx
  frontend/src/components/LogInForm.jsx
  frontend/src/components/NewSiteForm.jsx
  frontend/src/components/RegisterForm.jsx
  frontend/src/components/SiteFlexbox.jsx
  frontend/src/components/UserInfo.jsx
  frontend/src/layouts/GrowerLayout.jsx
  frontend/src/layouts/RetailerLayout.jsx
  frontend/src/pages/LogInPage.jsx
  frontend/src/pages/RegisterPage.jsx
  frontend/src/pages/SitePage.jsx
  frontend/src/pages/TermsPage.jsx
  frontend/src/pages/UserPage.jsx
  frontend/src/translations.json
  frontend/tests/components/LogInForm.test.jsx
  frontend/tests/components/RegisterForm.test.jsx
Labels: enhancement

#82 81 unit tests for internationalization
  frontend/src/App.jsx
  frontend/src/components/LangSelect.jsx
  frontend/tests/components/LangSelect.test.jsx
Labels: enhancement

#99 98 frontend unit tests fail on some time zones
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/need-help.md
  frontend/vite.config.js
  frontend/vitest.global-setup.js
Labels: bug, priority:medium

#96 95 backend unit tests to ci pipeline
  .github/workflows/ci.yml
  .github/workflows/staging.yml
Labels: enhancement

#102 97 frontend unit tests to ci pipeline
  .github/workflows/ci.yml
  frontend/vitest.global-setup.js
Labels: type:enhancement, priority:medium

#105 94 user can view a flower page
  frontend/src/components/FlowerModal.jsx
  frontend/src/components/grower/GrowerFlowerList.jsx
  frontend/src/components/retailer/RetailerFlowerList.jsx
  frontend/src/layouts/Grower.css
  frontend/src/translations.json
Labels: priority:high, type:feature
